local m_game = require "bs.lua.game"

function init(self)
	self.box = gui.get_node("box")
	self.button_back = gui.get_node("button-back")
	m_game.gui_init()
end

function on_message(self, message_id, message, sender)
	m_game.gui_message(self.box, message_id, message)
end

function on_input(self, action_id, action)
	if action_id == m_game.touch and action.pressed then
		if gui.pick_node(self.button_back, action.x, action.y) then
			m_game.gui_switch("start")
		end
	end
end
